# Generated by Django 3.0.4 on 2020-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('class_name', models.CharField(max_length=128)),
                ('class_title', models.CharField(max_length=128)),
                ('class_num', models.IntegerField()),
                ('class_people', models.CharField(max_length=256)),
                ('class_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'classes',
                'verbose_name_plural': 'classes',
                'ordering': ['class_time'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=128)),
                ('course_start', models.CharField(max_length=256)),
                ('course_end', models.CharField(max_length=128)),
                ('course_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'course',
                'ordering': ['course_time'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=128)),
                ('class_id', models.CharField(max_length=256)),
                ('course_id', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'student',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Work_Student',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(max_length=128)),
                ('stu_id', models.IntegerField(max_length=128)),
                ('end_src', models.CharField(max_length=128)),
                ('studentname', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=128)),
                ('work_src', models.CharField(max_length=128)),
                ('work_score', models.IntegerField(max_length=128)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'work2',
                'verbose_name_plural': 'work2',
                'ordering': ['c_time'],
            },
        ),
    ]
