# Generated by Django 3.0.4 on 2020-03-31 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_show', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work_Student',
        ),
    ]
