# Generated by Django 3.0.4 on 2020-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teacher',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Work_Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('teachername', models.CharField(max_length=128)),
                ('endtime', models.CharField(max_length=256)),
                ('desc', models.CharField(max_length=128)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'work1',
                'verbose_name_plural': 'work1',
                'ordering': ['c_time'],
            },
        ),
    ]
